import Head from "next/head";
import { Inter } from "@next/font/google";
import MiniProfiles from "@/components/MiniProfiles.component";
import { useContext } from "react";
import { UserContext } from "@/context/user.context";

const inter = Inter({ subsets: ["latin"] });

const basicDatas = [
  {
    id: 1,
    firstName: "Bonnie",
    lastName: "Green",
    initials: "BG",
    imageUrl:
      "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Visual Designer",
    company: "Google",
    openForWork: false,
    socials: [
      { facebook: "" },
      { linkedIn: "" },
      { gitHub: "" },
      { website: "" },
    ],
  },
  {
    id: 2,
    firstName: "Steve",
    lastName: "Oss",
    initials: "SO",
    imageUrl:
      "https://as2.ftcdn.net/v2/jpg/02/24/86/95/1000_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
    title: "Frontend Developer",
    company: "",
    openForWork: false,
    socials: [
      { facebook: "" },
      { linkedIn: "" },
      { gitHub: "" },
      { website: "" },
    ],
  },
  {
    id: 3,
    firstName: "Mike",
    lastName: "Miller",
    initials: "MM",
    imageUrl:
      "https://as2.ftcdn.net/v2/jpg/02/24/86/95/1000_F_224869519_aRaeLneqALfPNBzg0xxMZXghtvBXkfIA.jpg",
    title: "Frontend Developer",
    company: "",
    openForWork: false,
    socials: [
      { facebook: "" },
      { linkedIn: "" },
      { gitHub: "" },
      { website: "" },
    ],
  },
  // {
  //   id: 4,
  //   firstName: "Jen",
  //   lastName: "Lu",
  //   initials: "JL",
  //   imageUrl: "",
  //   title: "Frontend Developer",
  //   company: "",
  //   openForWork: false,
  //   socials: [
  //     { facebook: "" },
  //     { linkedIn: "" },
  //     { gitHub: "" },
  //     { website: "" },
  //   ],
  // },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MiniProfiles miniProfiles={basicDatas} />
      </main>
    </>
  );
}
